### ISSUE TITLE
Is there an error on the website? Or do we need to update the code?

### ISSUE THREAD

**Issue by tekinarslan** [dmitry-kostin/termin-buchen#21]
First of all, thanks for your time and effort.

Console say some errors. 

<img width="1330" alt="Screenshot 2024-01-31 at 12 19 18" src="https://github.com/dmitry-kostin/termin-buchen/assets/4000512/8cfa47f7-3d2c-4fb3-8505-977fbb5dfb78">

Regards

**Comment by dmitry-kostin** [comment]
Hey,
This appears to be an issue on their end, possibly due to a high volume of requests overwhelming their system. I've quickly reviewed it and haven't encountered the same error. Could you please attempt once more in an hour or so? If the problem persists, kindly share the specific use case you're executing script with, so I can investigate further

**Comment by tekinarslan** [comment]
Hey,
Thanks for your quick response. I tried one hour later but system didn't working. I think it's related with them. I am trying to get permanent settlement permit. If you know alternative ways, please let me know privately.
<img width="265" alt="Screenshot 2024-02-01 at 08 00 58" src="https://github.com/dmitry-kostin/termin-buchen/assets/4000512/59689673-c01c-4be8-b74b-bdf526c8686e">

**Comment by dmitry-kostin** [comment]
Hey there,

Sorry for the late response. Were you able to find your termin?

**Comment by tekinarslan** [comment]
Hello
No worries. I didn't find a termin :/ 
I think they was closed the apis.
